options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          script:
            #- export IMAGE_NAME=atlassianlabs/docker-node-jdk-chrome-firefox:latest
            #- docker build -t $IMAGE_NAME .
            #- docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            #- docker push $IMAGE_NAME
            - echo $TODAY
            - echo $DATE
  custom:
    deployment-to-hub-docker:
      - step:
          script:
            - export IMAGE_NAME=atlassianlabs/docker-node-jdk-chrome-firefox:latest
            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE_NAME